" Copied from https://github.com/OmniSharp/omnisharp-vim/wiki/Example-config

" Set this to 1 to use ultisnips for snippet handling
let g:using_snippets = 0

let s:path = expand('<sfile>:p:h') . '/'

function Source(filename)
  execute 'source '.fnameescape(s:path . a:filename)
endfunction

call plug#begin('~/.vim/plugged')
call Source('plugins.vim')
call plug#end()

call Source('settings.vim')

call Source('colors.vim')

call Source('omnisharp.vim')
